export * from './facultad.model';
export * from './jurado.model';
export * from './comite.model';
export * from './modalidad.model';
export * from './tiposolicitud.model';
export * from './proponente.model';
export * from './tipovinculacion.model';
export * from './departamento.model';
export * from './resultadosolicitud.model';
export * from './evaluacionsolicitud.model';
export * from './areainvestigacion.model';
export * from './solicitud.model';
export * from './comite-solicitud.model';
export * from './jurado-investigacion.model';
export * from './departamento-proponente.model';
export * from './recordatorio.model';
export * from './usuariojurado.model';

export * from './usuarioproponente.model';
